-- Each service has its own database for logical isolation
CREATE DATABASE IF NOT EXISTS bank_accounts DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS bank_transfers DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS bank_ledger   DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS bank_notifications DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS bank_users    DEFAULT CHARACTER SET utf8mb4;
